# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db8ddf773f0489643cf9ea053924d2d4d319bfa094066a31c4d283d8d18bfafef590647fe26bbfed448a6f03bb85657255d5d610db2992c215c63e9da58a3cdb

test:
  secret_key_base: ba8238a04d6cc738fee1cd409d2d247a50a093f8ba06e2e3733a6f0848b55e4ab5a65367d3103bcc7bd0758d203e07177fc5f41ad4f5e1aca31718f6317f2c91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
